name: Tests

on: [push, pull_request]

jobs:
  test_som:
    runs-on: ubuntu-20.04 # ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Tests
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          ant -e test

      - name: CheckStyle
        run: |
          ant -e checkstyle
      
      - name: Download Eclipse
        run: |
          export ECLIPSE_TAR=eclipse.tar.gz
          export ECLIPSE_URL=https://ftp.snt.utwente.nl/pub/software/eclipse/eclipse/downloads/drops4/R-4.23-202203080310/eclipse-SDK-4.23-linux-gtk-x86_64.tar.gz
          curl ${ECLIPSE_URL} -o ${ECLIPSE_TAR}
          tar -C ${GITHUB_WORKSPACE}/.. -xzf ${ECLIPSE_TAR}

      - name: Check Eclipse Format
        run: |
          export ECLIPSE_EXE=${GITHUB_WORKSPACE}/../eclipse/eclipse
          ant -e eclipseformat

# TODO readd - ant coverage-jars; ant coverage-report 
